server:
  port: 1111   # HTTP (Tomcat) port

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/Users/jiedaibao/Desktop/maidanla-config
#        git:
#          uri: https://github.com/zbliujia/config-repo