# Spring properties
spring:
  application:
     name: order-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password:
    write:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password:
    read:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/wuwo?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password:

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5555/eureka/

# HTTP Server
server:
  port: 0   # HTTP (Tomcat) port
