#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false
#
#zuul:
#  ignoredServices: "*"
#  routes:
#    #orders: /orders/**
#    wechat: /wechat/**
#
#
zuul:
  ignoredServices: "*"
  routes:
    wechat:
      path: /api/**
      #sensitiveHeaders: Cookie,Set-Cookie,Authorization
# 没有这个无法输出出来
logging:
  level: debug

spring:
  redis:
    host: 127.0.0.1
    port: 6379
