#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false
#
#zuul:
#  ignoredServices: "*"
#  routes:
#    #orders: /orders/**
#    wechat: /wechat/**
#
#
zuul:
  ignoredServices: "*"
  routes:
    wechat: /api/**

# 没有这个无法输出出来
logging:
  level: debug

